version: '3'
 
services:
  haproxy:
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config:/usr/local/etc/haproxy/
      - /etc/letsencrypt/:/etc/ssl/
    networks:
      - proxy-net

  web:
    image: nginx
    expose:
      - 80
    networks:
      - proxy-net

networks:
  proxy-net:
